// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wo4fnN1nzI3y7DXN29jHxRPQz9vIdYI',
    appId: '1:314728921112:web:4fad9e4e9e9fdadd1aeb6d',
    messagingSenderId: '314728921112',
    projectId: 'ilgaz-to-do',
    authDomain: 'ilgaz-to-do.firebaseapp.com',
    storageBucket: 'ilgaz-to-do.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQUveQK0LSNJFiTn9tDfWqrKRoVlGyIM',
    appId: '1:314728921112:android:53444107090d213e1aeb6d',
    messagingSenderId: '314728921112',
    projectId: 'ilgaz-to-do',
    storageBucket: 'ilgaz-to-do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwDOUyDZrGHTJvigXEfjU7fAvViNGNFQ',
    appId: '1:314728921112:ios:2f7e0c4f00ba65c01aeb6d',
    messagingSenderId: '314728921112',
    projectId: 'ilgaz-to-do',
    storageBucket: 'ilgaz-to-do.appspot.com',
    iosClientId: '314728921112-8n4ijiuahkrosrg6pot84tnrf2hbov1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcwDOUyDZrGHTJvigXEfjU7fAvViNGNFQ',
    appId: '1:314728921112:ios:8335ca251751fad61aeb6d',
    messagingSenderId: '314728921112',
    projectId: 'ilgaz-to-do',
    storageBucket: 'ilgaz-to-do.appspot.com',
    iosClientId: '314728921112-hrni03ras5qe0rnf1r56899ak6i155qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
